version: "3.9"

services:
  auth-service:
    build: .
    ports:
      - "8082:8000"
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - PORT=8000
      - JWT_SECRET=my-super-secret-key-minumum-32-chars-long
      - JWT_EXPIRY=1800
      - REFRESH_TOKEN_EXPIRY=604800
      - ENVIRONMENT=production
    depends_on:
      - auth-db
    networks:
      - auth-network

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5400:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - auth-network

volumes:
  auth-db-data:

networks:
  auth-network:
    driver: bridge
